apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    app: db
spec:
  containers:
    - image: redis:latest
      name: redis
      imagePullPolicy: Never
      ports:
        - containerPort: 6379
      volumeMounts:
        - mountPath: "/data"
          name: redis-database-storage
  volumes:
    - name: redis-database-storage
      persistentVolumeClaim:
        claimName: redis-database-claim
