apiVersion: v1
kind: Pod
metadata:
  name: postgres
  labels:
    app: db
spec:
  containers:
    - image: postgres:latest
      name: postgres
      imagePullPolicy: Never
      ports:
        - containerPort: 5432
      env:
        - name: POSTGRES_DB
          value: "kakaka"
        - name: POSTGRES_USER
          value: "default"
        - name: POSTGRES_PASSWORD
          value: "secret"
      volumeMounts:
        - mountPath: "/var/lib/postgresql/data"
          name: postgres-database-storage
  volumes:
    - name: postgres-database-storage
      persistentVolumeClaim:
        claimName: postgres-database-claim
